import { createElement } from '@lwc/engine-dom';
import OM_CalendarEventManager from 'c/oM_CalendarEventManager';

describe('c-o-m-calendar-event-manager', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-o-m-calendar-event-manager', {
            is: OM_CalendarEventManager
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});