public class ExchangeRateWrapper{
	public String result;	//success
	public String provider;	//https://www.exchangerate-api.com
	public Integer time_last_update_unix;	//1754092951
	public String time_last_update_utc;	//Sat, 02 Aug 2025 00:02:31 +0000
	public Integer time_next_update_unix;	//1754180461
	public String time_next_update_utc;	//Sun, 03 Aug 2025 00:21:01 +0000
	public Integer time_eol_unix;	//0
	public String base_code;	//USD
	public rates conversion_rates;
	public class rates {
		public Double USD;	//1
		public Double GBP;	//0.754341
		public Double MNT;	//3568.985024
		public Double MXN;	//18.879713
	}
}